# Generated by Django 4.2.16 on 2024-11-22 10:21

from django.db import migrations, models
import mycloud_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud_api', '0002_alter_file_size_alter_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=mycloud_api.models.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['upload_date'], name='mycloud_api_upload__4289eb_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user'], name='mycloud_api_user_id_cc3af2_idx'),
        ),
    ]
