# Generated by Django 4.2.16 on 2024-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud_api', '0004_userprofile_userfile_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
    ]
